### ISSUE TITLE
Bug with file download

### ISSUE THREAD

**Issue by gmioannou** [filefilego/filefilego-ui#14]
On windows Super light node, after the file is downloaded it remains locked by filefilego-ui

**Comment by filefilegoadmin** [comment]
Thanks for reporting the issue, working on it now, you can track the status here: https://github.com/orgs/filefilego/projects/3/views/1?pane=issue&itemId=33184442

**Comment by filefilegoadmin** [comment]
The issue is fixed in v0.2.2 https://github.com/filefilego/filefilego-ui/releases/tag/v0.2.2
Download the new binaries from https://filefilego.com/#download
